server:
  port: 0
spring:
  application:
    name: currency-converter
  eureka:
    instance:
      instance-id: ${spring.application.name}:${random.value}
    client:
      defaultZone: http://localhost:8761/eureka

