server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/konstantin-kharchenko/config-files.git
          default-label: master
          skipSslValidation: true
          username: konstantin-kharchenko
          password: bppb23-=
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
